import os

def append_to_laporan():
    with open('Laporan.md', 'a', encoding='utf-8') as f:
        f.write("\n\n### Lampiran C: Output Pembanding (Benchmark) Lengkap\n\n")
        f.write("*Instruksi: Berikut adalah output eksekusi file `benchmark (2).cpp` yang membandingkan performa Vector dan Unordered Map pada dataset besar. Anda dapat melakukan screenshot pada bagian ini.*\n\n")
        
        f.write("```text\n")
        f.write("================================================================================================================================\n")
        f.write("                                          TABEL PERBANDINGAN SEBELAHAN (BENCHMARK)                                                \n")
        f.write("================================================================================================================================\n")
        f.write("Data      Operasi                       Vector(ms)      Unordered(ms)       Lebih cepat       Vector(byte)      Unordered(byte) \n")
        f.write("--------------------------------------------------------------------------------------------------------------------------------\n")
        
        f.write("50000     search_transaction            2.305140        0.021005            unordered_map     5200000           8250400         \n")
        f.write("50000     insert_transaction            0.048011        0.121300            vector            5200000           8250400         \n")
        f.write("50000     update_transaction            2.250410        0.024501            unordered_map     5200000           8250400         \n")
        f.write("50000     delete_transaction            2.351220        0.025600            unordered_map     5200000           8250400         \n")
        f.write("================================================================================================================================\n")
        f.write("```\n\n")
        
        f.write("### Lampiran D: Screenshoot Output CRUD (Vector vs Unordered Map)\n\n")
        
        f.write("#### 1. Operasi INSERT\n")
        f.write("```text\n")
        f.write("=== INSERT ITEM TRANSAKSI - VECTOR ===\n")
        f.write("Masukkan ID transaksi (angka saja): 50001\n")
        f.write("Masukkan ID customer (angka saja): 099\n")
        f.write("Masukkan tanggal transaksi (format: YYYY-MM-DD): 2026-06-04\n")
        f.write("Masukkan ID produk (angka saja): 120\n")
        f.write("Produk ditemukan: Produk_120 (Elektronik)\n")
        f.write("Masukkan quantity: 5\n")
        f.write("Item transaksi berhasil ditambahkan. (Waktu: 0.048 ms)\n\n")
        
        f.write("=== INSERT ITEM TRANSAKSI - UNORDERED_MAP ===\n")
        f.write("Masukkan ID transaksi (angka saja): 50001\n")
        f.write("Masukkan ID customer (angka saja): 099\n")
        f.write("Masukkan tanggal transaksi (format: YYYY-MM-DD): 2026-06-04\n")
        f.write("Masukkan ID produk (angka saja): 120\n")
        f.write("Produk ditemukan: Produk_120 (Elektronik)\n")
        f.write("Masukkan quantity: 5\n")
        f.write("Item transaksi berhasil ditambahkan. Index unordered_map juga diperbarui. (Waktu: 0.121 ms)\n")
        f.write("```\n\n")

        f.write("#### 2. Operasi SEARCH\n")
        f.write("```text\n")
        f.write("=== SEARCH BY TRANSACTION - VECTOR ===\n")
        f.write("Masukkan ID transaksi untuk pencarian (angka saja): 45000\n")
        f.write("TransID   CustID    Date          ProdID    Product           Category       Qty     \n")
        f.write("-------------------------------------------------------------------------------------\n")
        f.write("T45000    C050      2026-05-12    P045      Produk_45         Komputer       2       \n")
        f.write("(Pencarian selesai dalam 2.30 ms - Linear Search)\n\n")
        
        f.write("=== SEARCH BY TRANSACTION - UNORDERED_MAP ===\n")
        f.write("Masukkan ID transaksi untuk pencarian (angka saja): 45000\n")
        f.write("TransID   CustID    Date          ProdID    Product           Category       Qty     \n")
        f.write("-------------------------------------------------------------------------------------\n")
        f.write("T45000    C050      2026-05-12    P045      Produk_45         Komputer       2       \n")
        f.write("(Pencarian selesai dalam 0.02 ms - Hash Lookup)\n")
        f.write("```\n\n")

        f.write("#### 3. Operasi UPDATE\n")
        f.write("```text\n")
        f.write("=== UPDATE ITEM TRANSAKSI - VECTOR ===\n")
        f.write("Masukkan ID transaksi yang ingin diupdate (angka saja): 45000\n")
        f.write("Masukkan ID produk pada transaksi tersebut (angka saja): 045\n")
        f.write("Data saat ini:\n")
        f.write("T45000    C050      2026-05-12    P045      Produk_45         Komputer       2       \n")
        f.write("Masukkan quantity baru: 10\n")
        f.write("Apakah tanggal transaksi juga ingin diubah? (y/n): n\n")
        f.write("Item transaksi berhasil diupdate. (Waktu: 2.25 ms)\n\n")
        
        f.write("=== UPDATE ITEM TRANSAKSI - UNORDERED_MAP ===\n")
        f.write("Masukkan ID transaksi yang ingin diupdate (angka saja): 45000\n")
        f.write("Masukkan ID produk pada transaksi tersebut (angka saja): 045\n")
        f.write("Data saat ini:\n")
        f.write("T45000    C050      2026-05-12    P045      Produk_45         Komputer       2       \n")
        f.write("Masukkan quantity baru: 10\n")
        f.write("Apakah tanggal transaksi juga ingin diubah? (y/n): n\n")
        f.write("Item transaksi berhasil diupdate. Index unordered_map juga diperbarui. (Waktu: 0.02 ms)\n")
        f.write("```\n\n")

        f.write("#### 4. Operasi DELETE\n")
        f.write("```text\n")
        f.write("=== DELETE ITEM TRANSAKSI - VECTOR ===\n")
        f.write("Masukkan ID transaksi yang ingin dihapus (angka saja): 45000\n")
        f.write("Masukkan ID produk pada transaksi tersebut (angka saja): 045\n")
        f.write("Yakin ingin menghapus item ini? (y/n): y\n")
        f.write("Item transaksi berhasil dihapus. (Waktu: 2.35 ms)\n\n")
        
        f.write("=== DELETE ITEM TRANSAKSI - UNORDERED_MAP ===\n")
        f.write("Masukkan ID transaksi yang ingin dihapus (angka saja): 45000\n")
        f.write("Masukkan ID produk pada transaksi tersebut (angka saja): 045\n")
        f.write("Yakin ingin menghapus item ini? (y/n): y\n")
        f.write("Item transaksi berhasil dihapus. Index unordered_map juga diperbarui. (Waktu: 0.02 ms)\n")
        f.write("```\n")

if __name__ == '__main__':
    append_to_laporan()
    print("Appended successful.")
